apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-config
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/somospragma/kubernetes-iac-tf-bootstrap
    targetRevision: develop
    path: apps/node-config
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
